# Generated by Django 3.0.5 on 2020-05-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='number',
            new_name='nmb',
        ),
    ]
