# Generated by Django 3.0.5 on 2020-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
